dubbo:
  #指定当前服务
  application:
    name: consumer
    qos-enable: false
  #注册中心
  registry:
    protocol: zookeeper
    address: 192.168.40.44:2181
  #配置consumer启动时检查，check为false时，启动不检查,超时配置
  #consumer中配置的是全局配置
  # 幂等【操作多少次结果都是一样的，如：查询、删除、修改】，在设计系统是应该设置成幂等的
  # 非幂等操作【和幂等对立，每次操作的结果不一样，如：新增，修改】，不能设置成重试
  consumer:
    check: false
    #重试次数，不算第一个
    retries: 3
#    timeout: 6000
